
add_defines("UNIT_TEST")
add_cxxflags("-fno-access-control")
add_packages("gtest")

target("test_rocksdb_store")
    set_kind("binary")
    add_files("test_rocksdb_store.cc")
    add_files("../rocksdb_store.cc")
    add_tests("pain_common")
    add_deps("pain_base")
    add_deps("pain_core")
    add_packages("rocksdb")
    add_packages("boost")
    add_packages("braft")
