---
# Deploy deva

- name: deploy/stop/clean deva
  hosts: deva
  vars:
    gflags:
      log_level: debug
  roles:
    - deva


# Deploy manusya

- name: deploy manusya
  hosts: manusya
  vars:
    gflags:
      log_level: info
  roles:
    - manusya

# Deploy jaeger
- name: deploy jaeger
  hosts: jaeger
  remote_user: root
  tags:
    - start
    - jaeger
    - start-jaeger
  tasks:
    - name: start jaeger
      community.docker.docker_container:
        name: pain-jaeger
        image: jaegertracing/all-in-one:latest
        ports:
          - "16686:16686"
          - "4317:4317"
          - "4318:4318"
          - "9411:9411"
        env:
          COLLECTOR_ZIPKIN_HTTP_PORT: "9411"

- name: stop jaeger
  hosts: jaeger
  remote_user: root
  tags:
    - stop
    - jaeger
    - stop-jaeger
  tasks:
    - name: stop jaeger
      community.docker.docker_container:
        name: pain-jaeger
        state: stopped

# Deploy prometheus
- name: deploy prometheus
  hosts: prometheus
  remote_user: root
  ignore_errors: yes
  roles:
    - { role: prometheus.prometheus.prometheus, when: '"start-prometheus" in ansible_run_tags'}
  tags:
    - prometheus
    - start-prometheus
  vars:
    prometheus_web_listen_address: "0.0.0.0:9090"
    prometheus_scrape_configs:
      - job_name: "prometheus"
        metrics_path: "/brpc_metrics"
        static_configs:
          - targets:
            - "{{ ansible_default_ipv4.address }}:8001"
            - "{{ ansible_default_ipv4.address }}:8002"
            - "{{ ansible_default_ipv4.address }}:8003"
            labels:
              env: deva
          - targets:
            - "{{ ansible_default_ipv4.address }}:8101"
            labels:
              env: manusya
