#!/bin/bash

PAIN_IP=$(hostname -I | awk '{print $1}')
PAIN_ASURA_ADDRESS="$PAIN_IP:8201"
PAIN_DEVA_ADDRESS="$PAIN_IP:8001,$PAIN_IP:8002,$PAIN_IP:8003"
PAIN_MANUSYA_ADDRESS="$PAIN_IP:8101"

echo "PAIN_IP: $PAIN_IP"
echo "PAIN_ASURA_ADDRESS: $PAIN_ASURA_ADDRESS"
echo "PAIN_DEVA_ADDRESS: $PAIN_DEVA_ADDRESS"
echo "PAIN_MANUSYA_ADDRESS: $PAIN_MANUSYA_ADDRESS"

export PAIN_IP
export PAIN_ASURA_ADDRESS
export PAIN_DEVA_ADDRESS
export PAIN_MANUSYA_ADDRESS
