target("deva")
    set_kind("binary")
    add_files("**.cc|test/**.cc")
    add_deps("pain_base")
    add_deps("pain_proto")
    add_packages("uuid_v4")
    add_packages("braft")
    add_packages("rocksdb")

includes("test")
