target("pain_base")
    set_kind("static")
    add_files("**.cc|test/**.cc")
    add_packages("boost", {public = true})
    add_packages("brpc", {public = true})
    add_packages("spdlog", {public = true})
    add_packages("opentelemetry-cpp", {public = true})
    add_packages("uuid_v4", {public = true})

includes("test")
